 --- Init ---
BrutalBevster
 --- Bot used 1285 milliseconds ---
-----------------------------------------------------------------------------
 --- Frame #1 ---
Traceback (most recent call last):
 --- Bot used 4 milliseconds ---
ERRORED!
Response received (if any):
Traceback (most recent call last):
 --- Bot was killed. Below is the rest of its output (if any): ---
  File "MyBot.py", line 100, in <module>
    hlt.send_frame(moves)
  File "/Users/simonbevan/PycharmProjects/halite/src/hlt.py", line 160, in send_frame
    send_string(' '.join(str(move.square.x) + ' ' + str(move.square.y) + ' ' + str(translate_cardinal(move.direction)) for move in moves))
  File "/Users/simonbevan/PycharmProjects/halite/src/hlt.py", line 160, in <genexpr>
    send_string(' '.join(str(move.square.x) + ' ' + str(move.square.y) + ' ' + str(translate_cardinal(move.direction)) for move in moves))
AttributeError: 'tuple' object has no attribute 'square'

 --- End bot output ---