 --- Init ---
/Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python: can't open file 'Random.py': [Errno 2] No such file or directory
 --- Bot used 14 milliseconds ---
-----------------------------------------------------------------------------
 --- Frame #1 ---

ERRORED!
No response received.